version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
  frontend:
    build: ./frontend
    container_name: frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
  db:
    image: 'postgres:alpine3.16'
    container_name: db
    env_file: ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  db_data:

