version: '3.8'
services:
  api:
    build: ./backend
    container_name: api
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
  web:
    build: ./frontend
    container_name: web
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  db:
    image: 'postgres:alpine3.16'
    container_name: 'db'
    env_file: ./backend/.env
    volumes: 
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
