name: prod

on: 
  push:
    branches: [ master ]

jobs: 
  Build:
    runs-on: self-hosted 
     
    steps: 
      - uses: actions/checkout@main 
      
      - name: Create .env
        run: |
          echo 'NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}' >> frontend/.env 
          echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> backend/.env 
          echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> backend/.env 
          echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> backend/.env 
          echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> backend/.env 
          echo 'GMAIL_USER=${{ secrets.GMAIL_USER }}' >> backend/.env
          echo 'GMAIL_PASS=${{ secrets.GMAIL_PASS }}' >> backend/.env 
          echo 'MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}' >> backend/.env 
          echo 'MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}' >> backend/.env
          echo 'MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }}' >> backend/.env
          echo 'MINIO_HOST=${{ secrets.MINIO_HOST }}' >> backend/.env
                
      - name: Clean 
        run: docker-compose -f ./docker-compose.prod.yml down & docker system prune -af
        
      - name: Build 
        run: docker-compose -f ./docker-compose.prod.yml build
        
      - name: Up
        run: docker-compose -f ./docker-compose.prod.yml up -d
